#lexik_jwt_authentication:
##    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
#    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
##    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
#    public_key: '%kernet.project_dir%/jwt/public.pem'
#    pass_phrase: '%env(JWT_PASSPHRASE)%'
#    token_ttl: 3600
