security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    access_denied_url:    ~ # Example: /foo/error403

    encoders:
        App\Entity\Utilisateurs: bcrypt
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_PARC: ROLE_PARC
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_USER]
        ROLE_PARC_ADMIN: [ROLE_PARC_ADMIN, ROLE_PARC, ROLE_USER]

    providers:
        my_in_memory_provider:
            memory:
                users:
                    admin_api:
                        password:           $2y$12$qcxKW2DmvSqeKHdR4RPnvOWNu19JndkoLQCorzoilu7.bevQ0tPVm
                        roles:              ROLE_API
        api_key_user_provider:
            id: App\Security\ApiKeyUserProvider
        our_db_provider:
            entity:
                class: App\Entity\Utilisateurs
                property: email
        in_memory: { memory: ~ }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/tests
            stateless: true
            # http_basic:
            #     realm: "Webservice API"
            #     provider: my_in_memory_provider
            simple_preauth:
                authenticator: App\Security\ApiKeyAuthenticator
                provider: api_key_user_provider
        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
                provider: our_db_provider
                default_target_path: /check_last_login
                always_use_default_target_path: true
                csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
            logout: true
            anonymous: true

        # default:
        #     anonymous: ~
        #     logout: ~
        #     guard:
        #         authenticators:
        #             - App\Security\TokenAuthenticator

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/check_last_login, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/tests, roles: ROLE_API }
        # - { path: ^/, roles: ROLE_USER }
        - { path: ^/parc/admin, roles: ROLE_PARC_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_REMEMBERED}
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
