parameters:
    cards_directory: "%kernel.project_dir%/public/uploads/cards"
    locale: '%env(APP_LOCALE)%'
    nomade_versions: '>=2.2.2'
    nomade_apk: 'http://wiilog.fr/dl/wiistock/recette/app-2-2-2.apk'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
          # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%cards_directory%'

    wiistock.specific_service:
        class: App\Service\SpecificService
        public: true

    App\EventListener\CardUploadListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    ref_article_listener:
        class: App\EventListener\RefArticleQuantityNotifier
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, lazy: true }
            - { name: doctrine.orm.entity_listener, event: preUpdate, lazy: true }
    article_listener:
        class: App\EventListener\ArticleQuantityNotifier
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, lazy: true }
            - { name: doctrine.orm.entity_listener, event: preUpdate, lazy: true }
